#!/bin/bash
# AUSTA Care Platform - Infrastructure Health Check Script
# Auto-generated by Infrastructure Orchestrator

set -e

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo "🏥 AUSTA Care Platform - Infrastructure Health Check"
echo "===================================================="
echo ""

# Function to check service
check_service() {
    local service_name=$1
    local check_command=$2

    echo -n "Checking $service_name... "
    if eval "$check_command" > /dev/null 2>&1; then
        echo -e "${GREEN}✅ Healthy${NC}"
        return 0
    else
        echo -e "${RED}❌ Unhealthy${NC}"
        return 1
    fi
}

# Check Docker
echo "🔍 Checking Docker..."
if ! docker info > /dev/null 2>&1; then
    echo -e "${RED}❌ Docker is not running${NC}"
    exit 1
fi
echo -e "${GREEN}✅ Docker is running${NC}"
echo ""

# Check containers
echo "🐳 Checking Docker Containers:"
echo "=============================="

check_service "PostgreSQL (5432)" "docker exec austa_postgres pg_isready -U austa"
check_service "Redis (6379)" "docker exec austa_redis redis-cli ping"
check_service "MongoDB (27017)" "docker exec austa_mongodb mongosh --eval 'db.adminCommand(\"ping\")'"
check_service "Kafka (9092)" "docker exec austa_kafka kafka-broker-api-versions --bootstrap-server localhost:9092"
check_service "FHIR Server (8090)" "curl -f http://localhost:8090/fhir/metadata"
check_service "Prometheus (9090)" "curl -f http://localhost:9090/-/healthy"
check_service "Grafana (3001)" "curl -f http://localhost:3001/api/health"
check_service "Jaeger (16686)" "curl -f http://localhost:14269/"
check_service "Elasticsearch (9200)" "curl -f http://localhost:9200"
check_service "Kibana (5601)" "curl -f http://localhost:5601/api/status"
check_service "MinIO (9000)" "curl -f http://localhost:9000/minio/health/live"

echo ""
echo "📊 Container Status:"
echo "==================="
docker ps --filter "name=austa_" --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"

echo ""
echo "💾 Volume Usage:"
echo "==============="
docker volume ls --filter "name=austa-care-platform" --format "table {{.Name}}\t{{.Driver}}"

echo ""
echo "🔗 Network Status:"
echo "=================="
docker network ls --filter "name=austa"

echo ""
echo -e "${GREEN}✅ Health check completed!${NC}"
