#!/bin/bash
# AUSTA Care Platform - Infrastructure Startup Script
# Auto-generated by Infrastructure Orchestrator
# Date: 2025-11-17

set -e

echo "🚀 AUSTA Care Platform - Infrastructure Deployment"
echo "=================================================="
echo ""

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Check if Docker is running
echo "🔍 Checking Docker status..."
if ! docker info > /dev/null 2>&1; then
    echo -e "${RED}❌ Docker is not running. Please start Docker Desktop or colima.${NC}"
    echo ""
    echo "To start Docker:"
    echo "  - Docker Desktop: Open the Docker Desktop application"
    echo "  - Colima: run 'colima start'"
    exit 1
fi
echo -e "${GREEN}✅ Docker is running${NC}"
echo ""

# Navigate to project root
cd "$(dirname "$0")/.."
PROJECT_ROOT=$(pwd)

echo "📍 Project root: $PROJECT_ROOT"
echo ""

# Start infrastructure services
echo "🐳 Starting infrastructure services..."
cd "$PROJECT_ROOT/austa-care-platform"

# Pull latest images
echo "📥 Pulling latest Docker images..."
docker-compose -f docker-compose.infrastructure.yml pull

# Start services
echo "🚀 Starting Docker containers..."
docker-compose -f docker-compose.infrastructure.yml up -d

echo ""
echo "⏳ Waiting for services to be healthy..."
sleep 10

# Check service health
echo ""
echo "🏥 Health Check Status:"
echo "======================"

# PostgreSQL
echo -n "PostgreSQL (5432)... "
if docker exec austa_postgres pg_isready -U austa > /dev/null 2>&1; then
    echo -e "${GREEN}✅ Healthy${NC}"
else
    echo -e "${YELLOW}⚠️  Starting up...${NC}"
fi

# Redis
echo -n "Redis (6379)... "
if docker exec austa_redis redis-cli ping > /dev/null 2>&1; then
    echo -e "${GREEN}✅ Healthy${NC}"
else
    echo -e "${YELLOW}⚠️  Starting up...${NC}"
fi

# MongoDB
echo -n "MongoDB (27017)... "
if docker exec austa_mongodb mongosh --eval "db.adminCommand('ping')" > /dev/null 2>&1; then
    echo -e "${GREEN}✅ Healthy${NC}"
else
    echo -e "${YELLOW}⚠️  Starting up...${NC}"
fi

# Kafka (takes longer to start)
echo -n "Kafka (9092)... "
if docker exec austa_kafka kafka-broker-api-versions --bootstrap-server localhost:9092 > /dev/null 2>&1; then
    echo -e "${GREEN}✅ Healthy${NC}"
else
    echo -e "${YELLOW}⚠️  Starting up (this may take 30-60 seconds)...${NC}"
fi

# FHIR Server
echo -n "FHIR Server (8090)... "
if curl -f http://localhost:8090/fhir/metadata > /dev/null 2>&1; then
    echo -e "${GREEN}✅ Healthy${NC}"
else
    echo -e "${YELLOW}⚠️  Starting up...${NC}"
fi

echo ""
echo "📊 Service URLs:"
echo "==============="
echo "PostgreSQL:     postgresql://austa:austa_password@localhost:5432/austa_care"
echo "Redis:          redis://localhost:6379"
echo "MongoDB:        mongodb://localhost:27017/austa_care"
echo "Kafka:          localhost:9092"
echo "Kafka UI:       http://localhost:8080"
echo "FHIR Server:    http://localhost:8090/fhir"
echo "Prometheus:     http://localhost:9090"
echo "Grafana:        http://localhost:3001 (admin/admin)"
echo "Jaeger:         http://localhost:16686"
echo "Elasticsearch:  http://localhost:9200"
echo "Kibana:         http://localhost:5601"
echo "MinIO Console:  http://localhost:9001 (minioadmin/minioadmin)"

echo ""
echo "🎯 Next Steps:"
echo "============="
echo "1. Run database migrations:"
echo "   cd backend && npx prisma migrate deploy"
echo ""
echo "2. Start the backend server:"
echo "   cd backend && npm run dev"
echo ""
echo "3. Monitor services:"
echo "   docker-compose -f austa-care-platform/docker-compose.infrastructure.yml logs -f"
echo ""
echo "4. Stop infrastructure:"
echo "   ./scripts/stop-infrastructure.sh"
echo ""

echo -e "${GREEN}✅ Infrastructure deployment completed!${NC}"
