#!/bin/bash
# AUSTA Care Platform - Infrastructure Shutdown Script
# Auto-generated by Infrastructure Orchestrator

set -e

echo "🛑 AUSTA Care Platform - Infrastructure Shutdown"
echo "==============================================="
echo ""

# Navigate to project root
cd "$(dirname "$0")/.."
PROJECT_ROOT=$(pwd)

echo "📍 Project root: $PROJECT_ROOT"
echo ""

# Stop infrastructure services
echo "🐳 Stopping infrastructure services..."
cd "$PROJECT_ROOT/austa-care-platform"
docker-compose -f docker-compose.infrastructure.yml down

echo ""
echo "✅ Infrastructure services stopped successfully!"
echo ""
echo "To remove volumes (WARNING: This will delete all data):"
echo "  docker-compose -f austa-care-platform/docker-compose.infrastructure.yml down -v"
