/**
 * Validation Module - Central Export
 *
 * This module provides comprehensive Zod validation schemas and middleware
 * for the AUSTA Care Platform API with Brazilian-specific validations.
 */

// Middleware
export {
  validate,
  validateBody,
  validateQuery,
  validateParams,
  validateFile,
  sanitizeInput,
} from './middleware/validate.middleware';

// User Schemas
export {
  createUserSchema,
  updateUserSchema,
  loginUserSchema,
  requestPasswordResetSchema,
  resetPasswordSchema,
  getUserByIdSchema,
  deleteUserSchema,
  listUsersSchema,
  UserRoleSchema,
  type CreateUserInput,
  type UpdateUserInput,
  type LoginUserInput,
  type RequestPasswordResetInput,
  type ResetPasswordInput,
  type GetUserByIdInput,
  type DeleteUserInput,
  type ListUsersInput,
  type UserRole,
} from './schemas/user.schema';

// Conversation Schemas
export {
  createConversationSchema,
  sendMessageSchema,
  getConversationSchema,
  listConversationsSchema,
  updateConversationSchema,
  deleteConversationSchema,
  getConversationMessagesSchema,
  rateMessageSchema,
  getConversationAnalyticsSchema,
  archiveConversationSchema,
  unarchiveConversationSchema,
  ConversationTypeSchema,
  MessageSenderSchema,
  AgentMoodSchema,
  type ConversationType,
  type MessageSender,
  type AgentMood,
  type CreateConversationInput,
  type SendMessageInput,
  type GetConversationInput,
  type ListConversationsInput,
  type UpdateConversationInput,
  type DeleteConversationInput,
  type GetConversationMessagesInput,
  type RateMessageInput,
  type GetConversationAnalyticsInput,
} from './schemas/conversation.schema';

// Health Data Schemas
export {
  createHealthDataSchema,
  getHealthDataSchema,
  listHealthDataSchema,
  updateHealthDataSchema,
  deleteHealthDataSchema,
  getHealthDataAnalyticsSchema,
  batchCreateHealthDataSchema,
  exportHealthDataSchema,
  getHealthDataTrendSchema,
  HealthDataTypeSchema,
  MeasurementUnitSchema,
  type HealthDataType,
  type MeasurementUnit,
  type CreateHealthDataInput,
  type GetHealthDataInput,
  type ListHealthDataInput,
  type UpdateHealthDataInput,
  type DeleteHealthDataInput,
  type GetHealthDataAnalyticsInput,
  type BatchCreateHealthDataInput,
  type ExportHealthDataInput,
} from './schemas/health-data.schema';

// Document Schemas
export {
  uploadDocumentSchema,
  getDocumentSchema,
  listDocumentsSchema,
  updateDocumentSchema,
  deleteDocumentSchema,
  shareDocumentSchema,
  downloadDocumentSchema,
  ocrDocumentSchema,
  verifyDocumentSchema,
  archiveDocumentSchema,
  restoreDocumentSchema,
  batchUploadDocumentsSchema,
  DocumentTypeSchema,
  DocumentStatusSchema,
  type DocumentType,
  type DocumentStatus,
  type UploadDocumentInput,
  type GetDocumentInput,
  type ListDocumentsInput,
  type UpdateDocumentInput,
  type DeleteDocumentInput,
  type ShareDocumentInput,
  type DownloadDocumentInput,
  type OcrDocumentInput,
  type VerifyDocumentInput,
} from './schemas/document.schema';

// Authorization Schemas
export {
  createAuthorizationSchema,
  getAuthorizationSchema,
  listAuthorizationsSchema,
  updateAuthorizationSchema,
  updateAuthorizationStatusSchema,
  cancelAuthorizationSchema,
  getAuthorizationTimelineSchema,
  exportAuthorizationSchema,
  batchCreateAuthorizationsSchema,
  getAuthorizationStatsSchema,
  AuthorizationTypeSchema,
  AuthorizationStatusSchema,
  UrgencyLevelSchema,
  type AuthorizationType,
  type AuthorizationStatus,
  type UrgencyLevel,
  type CreateAuthorizationInput,
  type GetAuthorizationInput,
  type ListAuthorizationsInput,
  type UpdateAuthorizationInput,
  type UpdateAuthorizationStatusInput,
  type CancelAuthorizationInput,
} from './schemas/authorization.schema';

// Gamification Schemas
export {
  recordActionSchema,
  getGamificationProfileSchema,
  getLeaderboardSchema,
  getAchievementsSchema,
  unlockAchievementSchema,
  getQuestsSchema,
  startQuestSchema,
  completeQuestSchema,
  abandonQuestSchema,
  claimRewardSchema,
  getRewardsSchema,
  updateStreakSchema,
  getGamificationStatsSchema,
  setDailyGoalSchema,
  updateDailyGoalProgressSchema,
  shareAchievementSchema,
  challengeFriendSchema,
  acceptChallengeSchema,
  declineChallengeSchema,
  AchievementTypeSchema,
  AchievementRaritySchema,
  QuestStatusSchema,
  QuestDifficultySchema,
  RewardTypeSchema,
  type AchievementType,
  type AchievementRarity,
  type QuestStatus,
  type QuestDifficulty,
  type RewardType,
  type RecordActionInput,
  type GetLeaderboardInput,
  type GetAchievementsInput,
  type GetQuestsInput,
  type CompleteQuestInput,
  type ClaimRewardInput,
} from './schemas/gamification.schema';

// Admin Schemas
export {
  getSystemMetricsSchema,
  getAuditLogsSchema,
  manageUserRoleSchema,
  suspendUserSchema,
  reactivateUserSchema,
  getSystemHealthSchema,
  configureSystemSettingsSchema,
  getFeatureFlagsSchema,
  updateFeatureFlagSchema,
  exportDataSchema,
  getUserAnalyticsSchema,
  sendSystemNotificationSchema,
  manageApiKeySchema,
  revokeApiKeySchema,
  getErrorLogsSchema,
  MetricTypeSchema,
  UserActionTypeSchema,
  type MetricType,
  type UserActionType,
  type GetSystemMetricsInput,
  type GetAuditLogsInput,
  type ManageUserRoleInput,
  type SuspendUserInput,
  type ConfigureSystemSettingsInput,
  type UpdateFeatureFlagInput,
  type SendSystemNotificationInput,
} from './schemas/admin.schema';
